DROP TABLE JAVA_USUARIO;
DROP TABLE JAVA_BILHETE;

CREATE TABLE JAVA_USUARIO (
NOME VARCHAR2(50),
CPF VARCHAR2(14),
TIPO VARCHAR2(30)
);

CREATE TABLE JAVA_BILHETE(
NUMERO NUMBER,
CPF VARCHAR2(14),
SALDO NUMBER(10,2),
VALORPASSAGEM NUMBER (10,2)
);


